[services]
[services.api]
name = "api"
dockerfile = "./Dockerfile"
startCommand = "npm start"
healthcheckPath = "/api/health"
port = 3000

[services.api.variables]
NODE_ENV = "production"
MONGODB_URI = "mongodb+srv://nathanmaulini167_db_user:z5SfFNxe2PQJHnXt@cluster0.y6ghewc.mongodb.net/hopital-pourtales?appName=Cluster0"

